### PR TITLE
Added use of EXTRA_VERIFY_ARGS when verifying project.

### PR DESCRIPTION
**Pull request by cmumford**
This allows users travis-ci-arduino users to insert arguments
into the verification step - i.e.:

    arduino --verify ...

**Note**: I did quite a lot of experimentation with platform.local.txt, but could never get a solution which used that to work. My guess is that there is one in the board *.zip file, and only it is being used. I even tried to hard-code the value into ~/arduino_ide/hardware/arduino/avr/platform.txt, but it was ignored.

Thank you for creating a pull request to contribute to Adafruit's GitHub code!
Before you open the request please review the following guidelines and tips to
help it be more easily integrated:

- **Describe the scope of your change--i.e. what the change does and what parts
  of the code were modified.**  This will help us understand any risks of integrating
  the code.

   Will insert extra parameters when invoking arduino defined by EXTRA_VERIFY_ARGS.

- **Describe any known limitations with your change.**  For example if the change
  doesn't apply to a supported platform of the library please mention it.

  Is backward compatible if EXTRA_VERIFY_ARGS is not defined.

- **Please run any tests or examples that can exercise your modified code.**  We
  strive to not break users of the code and running tests/examples helps with this
  process.

  Done (many times). This is my change that uses this new variable: https://github.com/cmumford/sparetheair/commit/44203170ced403a6d688caa1a58e2f777a072da7

Thank you again for contributing!  We will try to test and integrate the change
as soon as we can, but be aware we have many GitHub repositories to manage and
can't immediately respond to every request.  There is no need to bump or check in
on a pull request (it will clutter the discussion of the request).

Also don't be worried if the request is closed or not integrated--sometimes the
priorities of Adafruit's GitHub code (education, ease of use) might not match the
priorities of the pull request.  Don't fret, the open source community thrives on
forks and GitHub makes it easy to keep your changes in a forked repo.

After reviewing the guidelines above you can delete this text from the pull request.

### CODE REVIEW

**Comment by eddyp** [comment]
> This allows users travis-ci-arduino users to insert arguments
> into the verification step - i.e.:
> 
> ```
> arduino --verify ...
> ```

Can you extend a little the use case?

I would like to fail my builds if the size of used global vars is past a percent of the entire RAM (to prevent stack or heap growth to overwrite other data such as .data, .bss or each other). Would this extra test be possible? What are those extra arguments in your case?

**Comment by cmumford** [comment]
@eddyp I don't know the command line arguments to `arduino` well enough, but if there is a command-line argument to do this, then the change should allow it. Check out [ARDUINO(1) Manual Page](https://github.com/arduino/Arduino/blob/master/build/shared/manpage.adoc) - only those parameters can be used. I suggest you look at the various preferences (i.e. `--get-pref`).

**Comment by cmumford** [comment]
I rebased this change on adafruit:master because that branch had a few force-pushes.

**Comment by tekktrik** [comment]
Hi @cmumford, is this change still something that's needed?  Does it still work, or would testing be needed?

**Comment by cmumford** [comment]
It's been too long, so I don't know if it still works. I don't need it.

**Pull request closed without merging**
