### PR TITLE
Use the latest Arduino IDE version

### PR DESCRIPTION
**Pull request by platisd**
As of today, the latest Arduino IDE version is **1.8.11** which includes
several bug-fixes and enhancements.

### CODE REVIEW

**Comment by ladyada** [comment]
this is ok but FYI we've moved to actions - its much faster and uses the more modern ci

**Comment by platisd** [comment]
> this is ok but FYI we've moved to actions - its much faster and uses the more modern ci

Ah, good to know! Is this still being actively maintained or should we also consider moving to actions too?

**Comment by ladyada** [comment]
its still sorta being maintained but really we strongly recommend moving to actions...
https://github.com/adafruit/Adafruit_ILI9341/tree/master/.github/workflows
is a good example workflow you can use!

**Comment by platisd** [comment]
Great! Will consider it, thanks!

**Pull request merged**
