### PR TITLE
move all_platforms to its own file

### PR DESCRIPTION
**Pull request by hathach**
move `ALL_PLATFORMS` to its own file all_platforms.py to make it easier for other repo to re-use the definitions. This is sometime is useful for other repo without maintaining the list locally.

### CODE REVIEW

**Comment by brentru** [comment]
@hathach @ladyada  Are we still interested in this PR? I think it's great for maintainability and user-contributions.

**Comment by ladyada** [comment]
yah sorry i didnt see this, its ok but will need conflicts resolved

**Comment by hathach** [comment]
ah, I forgot about this as well, will update & resolve the conflict soon ...

**Comment by ladyada** [comment]
@hathach wanna try now that you're done with some recent projects?

**Comment by hathach** [comment]
@ladyada yeah, just bump it up to lastest and resolve conflict. Should be good for review.

**Pull request merged**
